import type { Metadata } from "next";
import { Oxanium } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Bruti Group",
  description: "Generated by create next app",
};

const oxanium = Oxanium({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${oxanium.className} dark`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
